/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Airplane;
import Business.Customer;
import javax.swing.JPanel;

/**
 *
 *  @author lENOVO PC
 */
public class BookingConfirmation extends javax.swing.JPanel {

    /**
     * Creates new form BookingConfirmation
     */
    private Customer customer;
    private JPanel userprocesscontainer;
    private Airplane airplane;
    public BookingConfirmation(JPanel userprocesscontainer,Airplane airplane,Customer customer) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airplane=airplane;
        this.customer=customer;
        display();
    }
    private void display(){
        int seatnumber = customer.getSeetNumber();
        SEATNUMBER_Textfield.setText(String.valueOf(seatnumber));
        String seattype = customer.getSeatType();
        SEATTYPE_Textfield.setText(seattype);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TicketsbookedLbl = new javax.swing.JLabel();
        SEATNUMBERLbl = new javax.swing.JLabel();
        SEATTYPELbl = new javax.swing.JLabel();
        SEATNUMBER_Textfield = new javax.swing.JTextField();
        SEATTYPE_Textfield = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jLabel1.setText("Booking Confirmation");

        TicketsbookedLbl.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        TicketsbookedLbl.setText("Ticket Booked");

        SEATNUMBERLbl.setText("SEAT NUMBER");

        SEATTYPELbl.setText("SEAT TYPE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SEATNUMBERLbl)
                        .addGap(35, 35, 35)
                        .addComponent(SEATNUMBER_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(TicketsbookedLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SEATTYPELbl)
                        .addGap(52, 52, 52)
                        .addComponent(SEATTYPE_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(TicketsbookedLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEATNUMBERLbl)
                    .addComponent(SEATNUMBER_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEATTYPELbl)
                    .addComponent(SEATTYPE_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SEATNUMBERLbl;
    private javax.swing.JTextField SEATNUMBER_Textfield;
    private javax.swing.JLabel SEATTYPELbl;
    private javax.swing.JTextField SEATTYPE_Textfield;
    private javax.swing.JLabel TicketsbookedLbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
