/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Customer;
import UserInterface.AirlinerRole.AirlinerWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 *  @author lENOVO PC
 */
public class ChooseFromAirlines extends javax.swing.JPanel {

    /**
     * Creates new form ChooseFromAirlines
     */
    private Customer customer;
    private JPanel userprocesscontainer;
    private AirlinerDirectory airlinerdirectory;
    public ChooseFromAirlines(JPanel userprocesscontainer,AirlinerDirectory airlinerdirectory,Customer customer) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airlinerdirectory = airlinerdirectory;
        this.customer=customer;
        
        airlinerComboBox1.removeAllItems();
       for(Airliner airliner : airlinerdirectory.getAirlinerDirectory()) {
           airlinerComboBox1.addItem(airliner);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseairlinesLbl = new javax.swing.JLabel();
        airlinesnameLbl = new javax.swing.JLabel();
        airlinerComboBox1 = new javax.swing.JComboBox();
        goBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 51));

        chooseairlinesLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        chooseairlinesLbl.setText("Choose From Airlines");

        airlinesnameLbl.setText("AIRLINES NAME");

        airlinerComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        goBtn.setText("GO>>>");
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(chooseairlinesLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(airlinesnameLbl)
                        .addGap(28, 28, 28)
                        .addComponent(airlinerComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(goBtn)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(chooseairlinesLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinesnameLbl)
                    .addComponent(airlinerComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBtn))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        // TODO add your handling code here:
         Airliner airliner = (Airliner)airlinerComboBox1.getSelectedItem();
       ChooseFromAirplanes swajp = new ChooseFromAirplanes(userprocesscontainer, airliner,customer);
        userprocesscontainer.add("ChooseFromAirplanes",swajp);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_goBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airlinerComboBox1;
    private javax.swing.JLabel airlinesnameLbl;
    private javax.swing.JLabel chooseairlinesLbl;
    private javax.swing.JButton goBtn;
    // End of variables declaration//GEN-END:variables
}
