/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.AirlinerDirectory;
import Business.Customer;
import Business.CustomerDirectory;
import UserInterface.AirlinerRole.ManageAirplaneCatalogJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class ManageCustomers extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomers
     */
    private Customer customer;
    private JPanel userprocesscontainer;
    private AirlinerDirectory airlinerdirectory;
    private CustomerDirectory cust1;
    //private CustomerDirectory customerdirectory;
    public ManageCustomers(JPanel userprocesscontainer,AirlinerDirectory airlinerdirectory,CustomerDirectory cust1,Customer customer) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airlinerdirectory=airlinerdirectory;
        this.cust1=cust1;
        this.customer=customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerprofileLbl = new javax.swing.JLabel();
        customeridLbl = new javax.swing.JLabel();
        firstnameLbl = new javax.swing.JLabel();
        lastnameLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        customerid_Textfield = new javax.swing.JTextField();
        firstname_Textfield = new javax.swing.JTextField();
        lastname_Textfield = new javax.swing.JTextField();
        address_Textfield = new javax.swing.JTextField();
        sexLbl = new javax.swing.JLabel();
        sexF_Radiobutton = new javax.swing.JRadioButton();
        createcustomerBtn = new javax.swing.JButton();
        sexM_Radiobutton = new javax.swing.JRadioButton();
        backbutton = new javax.swing.JButton();
        viewcustomerprofileBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        customerprofileLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        customerprofileLbl.setText("Customer Profile");

        customeridLbl.setText("Customer Id");

        firstnameLbl.setText("First Name");

        lastnameLbl.setText("Last Name");

        addressLbl.setText("Address");

        address_Textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_TextfieldActionPerformed(evt);
            }
        });

        sexLbl.setText("Sex");

        sexF_Radiobutton.setText("F");
        sexF_Radiobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexF_RadiobuttonMouseClicked(evt);
            }
        });

        createcustomerBtn.setText("Create");
        createcustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createcustomerBtnActionPerformed(evt);
            }
        });

        sexM_Radiobutton.setText("M");
        sexM_Radiobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sexM_RadiobuttonMouseClicked(evt);
            }
        });

        backbutton.setText("<<back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        viewcustomerprofileBtn.setText("View Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(customerprofileLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sexLbl)
                                .addComponent(customeridLbl)
                                .addComponent(firstnameLbl)
                                .addComponent(lastnameLbl)
                                .addComponent(addressLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backbutton)
                                .addGap(20, 20, 20)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(address_Textfield)
                            .addComponent(lastname_Textfield)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sexF_Radiobutton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(createcustomerBtn)
                                .addGap(49, 49, 49))
                            .addComponent(customerid_Textfield)
                            .addComponent(firstname_Textfield))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexM_Radiobutton)
                    .addComponent(viewcustomerprofileBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(customerprofileLbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customeridLbl)
                            .addComponent(customerid_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstnameLbl)
                            .addComponent(firstname_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameLbl)
                            .addComponent(lastname_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addressLbl)
                            .addComponent(address_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(sexLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(sexM_Radiobutton))))
                    .addComponent(sexF_Radiobutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbutton)
                    .addComponent(createcustomerBtn)
                    .addComponent(viewcustomerprofileBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void address_TextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_TextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_TextfieldActionPerformed

    private void createcustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createcustomerBtnActionPerformed
        // TODO add your handling code here:
//        try{
//            if(!customerid_Textfield.getText().equals("") && !firstname_Textfield.getText().equals("") && !lastname_Textfield.equals("") && !address_Textfield.equals("") && !sexF_Radiobutton.equals("")){
                //Double.parseDouble(txtPrice.getText());
                //Integer.parseInt(txtAvailablity.getText());
                Customer c = cust1.addCustomer();
            c.setCustomerId(customerid_Textfield.getText());
            c.setFirstName(firstname_Textfield.getText());
            c.setLastName(lastname_Textfield.getText());
            c.setAddress(address_Textfield.getText());
            
            
            c.setSex(sexF_Radiobutton.getText());
             c.setSex(sexM_Radiobutton.getText());
            
            JOptionPane.showMessageDialog(null, "Customer Created Successfully");
//            customerid_Textfield.setText("");
//            firstname_Textfield.setText("");
//            lastname_Textfield.setText("");
//            address_Textfield.setText("");
//            sex_Radiobutton.setText("");
            
            
            
        
    }//GEN-LAST:event_createcustomerBtnActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backbuttonActionPerformed

    private void sexF_RadiobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexF_RadiobuttonMouseClicked
        // TODO add your handling code here:
        sexM_Radiobutton.setSelected(false);
    }//GEN-LAST:event_sexF_RadiobuttonMouseClicked

    private void sexM_RadiobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sexM_RadiobuttonMouseClicked
        // TODO add your handling code here:
        sexF_Radiobutton.setSelected(false);
    }//GEN-LAST:event_sexM_RadiobuttonMouseClicked
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField address_Textfield;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton createcustomerBtn;
    private javax.swing.JLabel customeridLbl;
    private javax.swing.JTextField customerid_Textfield;
    private javax.swing.JLabel customerprofileLbl;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JTextField firstname_Textfield;
    private javax.swing.JLabel lastnameLbl;
    private javax.swing.JTextField lastname_Textfield;
    private javax.swing.JRadioButton sexF_Radiobutton;
    private javax.swing.JLabel sexLbl;
    private javax.swing.JRadioButton sexM_Radiobutton;
    private javax.swing.JButton viewcustomerprofileBtn;
    // End of variables declaration//GEN-END:variables
}
