/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Airliner;
import Business.Airplane;
import Business.Customer;
import UserInterface.AirlinerRole.ViewAirplaneDetailJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 *  @author lENOVO PC
 */
public class SearchThroughSeatsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchThroughSeatsJPanel
     */
    private Customer customer;
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public SearchThroughSeatsJPanel(JPanel userprocesscontainer,Airliner airliner,Customer customer) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
        this.customer=customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modalidLbl = new javax.swing.JLabel();
        searchthroughseats = new javax.swing.JLabel();
        modalid_Textfield = new javax.swing.JTextField();
        searchnowBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        modalidLbl.setText("Model Number");

        searchthroughseats.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        searchthroughseats.setText("Search Through Seats");

        searchnowBtn.setText("Search Now>>>");
        searchnowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnowBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchthroughseats)
                    .addComponent(backBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modalidLbl)
                        .addGap(40, 40, 40)
                        .addComponent(modalid_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchnowBtn))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(searchthroughseats)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modalidLbl)
                    .addComponent(modalid_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(searchnowBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchnowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnowBtnActionPerformed
        // TODO add your handling code here:
        Airplane airplane;
        int AirplaneId = Integer.parseInt(modalid_Textfield.getText());
        airplane = airliner.getAirplaneCatalog().searchAirplane(AirplaneId);
        SeatSelectionJPanel seat_selection = new SeatSelectionJPanel(userprocesscontainer, airplane,customer);
        userprocesscontainer.add("SeatSelectionJPanel", seat_selection);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_searchnowBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel modalidLbl;
    private javax.swing.JTextField modalid_Textfield;
    private javax.swing.JButton searchnowBtn;
    private javax.swing.JLabel searchthroughseats;
    // End of variables declaration//GEN-END:variables
}
