/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CustomerRole;

import Business.Airliner;
import Business.Airplane;
import Business.Customer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import UserInterface.AirlinerRole.ManageAirplaneCatalogJPanel;
import UserInterface.AirlinerRole.SearchForAirplaneJPanel;
import java.awt.CardLayout;

/**
 *
 *  @author lENOVO PC
 */
public class ViewAirplaneCatalog extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneCatalog
     */
    private Customer customer;
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public ViewAirplaneCatalog(JPanel userprocesscontainer,Airliner airliner,Customer customer) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
        this.customer=customer;
        
        airlinername1_Textfield.setText(airliner.getAirlinerName());
        refreshTable();
    }
public void refreshTable() {
        int rowCount = viewAirplaneCatalogTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)viewAirplaneCatalogTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Airplane ap : airliner.getAirplaneCatalog().getAirplaneCatalog()) {
            Object row[] = new Object[7];
            row[0] = ap;
            row[1] = ap.getAirlinerCode();
            row[2] = ap.getPrice();
            row[3] = ap.getSource();
            row[4] = ap.getDestination();
            row[5] = ap.getDate();
            row[6] = ap.getPreferred();
            
            model.addRow(row);
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewairplanecatalogLbl = new javax.swing.JLabel();
        airlinername1Lbl = new javax.swing.JLabel();
        airlinername1_Textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewAirplaneCatalogTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 51));

        viewairplanecatalogLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        viewairplanecatalogLbl.setText("View Airplane Catalog");

        airlinername1Lbl.setText("Airliner");

        viewAirplaneCatalogTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airplane Name", "Model Id", "Price", "Source", "Destination", "Date", "Preferred Time"
            }
        ));
        jScrollPane1.setViewportView(viewAirplaneCatalogTable);

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search seats");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(airlinername1Lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airlinername1_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backBtn)
                        .addGap(26, 26, 26)
                        .addComponent(searchBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(viewairplanecatalogLbl)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewairplanecatalogLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(airlinername1Lbl)
                .addGap(9, 9, 9)
                .addComponent(airlinername1_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(searchBtn))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        SearchThroughSeatsJPanel search_through_seats = new SearchThroughSeatsJPanel(userprocesscontainer, airliner,customer);
        userprocesscontainer.add("SearchThroughSeatsJPanel", search_through_seats);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
        
    }//GEN-LAST:event_searchBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinername1Lbl;
    private javax.swing.JTextField airlinername1_Textfield;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTable viewAirplaneCatalogTable;
    private javax.swing.JLabel viewairplanecatalogLbl;
    // End of variables declaration//GEN-END:variables
}
