/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.airliner;

import Business.airliner;
import Business.airliner_directory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class AddAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddAirlinerJPanel
     */
    private airliner_directory airliner1;
    private JPanel RightjPanel;
    public AddAirlinerJPanel(JPanel RightjPanel,airliner_directory airliner1) {
        initComponents();
        this.airliner1=airliner1;
        this.RightjPanel=RightjPanel;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblairlinername = new javax.swing.JLabel();
        lblairliner = new javax.swing.JLabel();
        txtairlinername = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        lblairlinername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblairlinername.setText("ADD AIRLINER ");

        lblairliner.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblairliner.setText("Enter Airliner Name:");

        btnback.setForeground(new java.awt.Color(204, 0, 0));
        btnback.setText(">>BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnadd.setForeground(new java.awt.Color(204, 0, 0));
        btnadd.setText("Add Airliner");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(lblairlinername))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblairliner)
                                .addGap(126, 126, 126)
                                .addComponent(txtairlinername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblairlinername)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblairliner)
                    .addComponent(txtairlinername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btnadd)
                .addGap(18, 18, 18)
                .addComponent(btnback)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        airliner a = airliner1.addairliner();
        a.setAirlinerName(txtairlinername.getText());
        
        JOptionPane.showMessageDialog(null, "Supplier successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        RightjPanel.remove(this);
        Component[] componentArray = RightjPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirlinerManagerJPanel Panel = (AirlinerManagerJPanel) component;
        Panel.populate();
        CardLayout layout = (CardLayout) RightjPanel.getLayout();
        layout.previous(RightjPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel lblairliner;
    private javax.swing.JLabel lblairlinername;
    private javax.swing.JTextField txtairlinername;
    // End of variables declaration//GEN-END:variables
}
