/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.airliner;

import Business.airliner;
import Business.airliner_directory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class AddAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddAirlinerJPanel
     */
    private airliner_directory airliner1;
    private JPanel RightjPanel;
    public AddAirlinerJPanel(JPanel RightjPanel,airliner_directory airliner1) {
        initComponents();
        this.airliner1=airliner1;
        this.RightjPanel=RightjPanel;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblairlinername = new javax.swing.JLabel();
        lblairliner = new javax.swing.JLabel();
        txtairlinername = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 51));

        lblairlinername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblairlinername.setText("ADD AIRLINER NAMES");

        lblairliner.setText("Enter Airliner Name:");

        btnback.setText("<<BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnadd.setText("Add Airliner");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblairliner)
                    .addComponent(btnback))
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblairlinername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnadd)
                    .addComponent(txtairlinername))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblairlinername)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblairliner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtairlinername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(btnadd))
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        airliner a = airliner1.addairliner();
        a.setAirlinerName(txtairlinername.getText());
        
        JOptionPane.showMessageDialog(null, "Airliners successfully added", "Added", JOptionPane.INFORMATION_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        RightjPanel.remove(this);
        Component[] componentArray = RightjPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirlinerManagerJPanel Panel = (AirlinerManagerJPanel) component;
        Panel.populate();
        CardLayout layout = (CardLayout) RightjPanel.getLayout();
        layout.previous(RightjPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel lblairliner;
    private javax.swing.JLabel lblairlinername;
    private javax.swing.JTextField txtairlinername;
    // End of variables declaration//GEN-END:variables
}
