/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customers;

import Business.airliner;
import Business.airliner_directory;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class ChooseAirplanes extends javax.swing.JPanel {

    /**
     * Creates new form ChooseAirplanes
     */
    private JPanel rightjpanel;
    private airliner air_liner;
    
    public ChooseAirplanes(JPanel rightjpanel,airliner air_liner) {
        initComponents();
        this.rightjpanel=rightjpanel;
        this.air_liner=air_liner;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnviewflight = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        btnviewflight.setText("View Flight Details");
        btnviewflight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewflightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(btnviewflight)
                .addContainerGap(730, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnviewflight)
                .addContainerGap(480, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewflightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewflightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewflightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnviewflight;
    // End of variables declaration//GEN-END:variables
}
