/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.customers;

import Business.airliner_directory;
import Business.CustomerDirectory;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class WorkAreaPanel extends javax.swing.JPanel {
    
    private JPanel rightjpanel;
    private airliner_directory airlinerlist;
    private CustomerDirectory custdir;

    /**
     * Creates new form WorkAreaJPanel
     */
    public WorkAreaPanel(JPanel rightjpanel,airliner_directory airlinerlist,CustomerDirectory custdir) {
        initComponents();
        this.rightjpanel=rightjpanel;
        this.airlinerlist=airlinerlist;
        this.custdir=custdir;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncp = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 51, 0));

        jLabel1.setText("WORK AREA OF CUSTOMER");

        btncp.setText("Create Profile");
        btncp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpActionPerformed(evt);
            }
        });

        btnBook.setText("BOOK");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(479, 479, 479)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncp))
                .addContainerGap(446, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(btncp)
                .addGap(36, 36, 36)
                .addComponent(btnBook)
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpActionPerformed
        // TODO add your handling code here:
        CustomerProfile custp = new CustomerProfile(rightjpanel, airlinerlist,custdir);
        rightjpanel.add("CustomerProfile", custp);
        CardLayout layout = (CardLayout)rightjpanel.getLayout();
        layout.next(rightjpanel);
      
    }//GEN-LAST:event_btncpActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        ChooseAirlines chooseairlines = new ChooseAirlines(rightjpanel,airlinerlist);
        rightjpanel.add("ChooseAirlines",chooseairlines);
        CardLayout layout = (CardLayout)rightjpanel.getLayout();
        layout.next(rightjpanel);
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btncp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
