/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgencyRole;

import Business.AirlinerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Airliner;

/**
 *
 *  @author lENOVO PC
 */
public class AddAirliner extends javax.swing.JPanel {

    /**
     * Creates new form AddAirliner
     */
    private JPanel userprocesscontainer;
    private AirlinerDirectory airlinedirectory;
    public AddAirliner(JPanel userprocesscontainer,AirlinerDirectory airlinedirectory) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airlinedirectory=airlinedirectory;
    }
    
    public void backAction(){
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirliners manageSuppliersJPanel = (ManageAirliners) component;
        manageSuppliersJPanel.refreshTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newairlinerLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        airlinername_Textfield = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        addairlinerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        newairlinerLbl.setText("New Airliner");

        nameLbl.setText("NAME");

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addairlinerBtn.setText("Add Airliner");
        addairlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addairlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addGap(33, 33, 33)
                            .addComponent(addairlinerBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(nameLbl)
                            .addGap(41, 41, 41)
                            .addComponent(airlinername_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newairlinerLbl))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(newairlinerLbl)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(airlinername_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addairlinerBtn))
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addairlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addairlinerBtnActionPerformed
        // TODO add your handling code here:
        Airliner airliner = airlinedirectory.addAirliner();
        airliner.setAirlinerName(airlinername_Textfield.getText());
        
        JOptionPane.showMessageDialog(null, "Airliner successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_addairlinerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addairlinerBtn;
    private javax.swing.JTextField airlinername_Textfield;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel newairlinerLbl;
    // End of variables declaration//GEN-END:variables
}
