/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgencyRole;

import javax.swing.JPanel;
import Business.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import Business.Airliner;
import javax.swing.table.DefaultTableModel;

/**
 *
 *  @author lENOVO PC
 */
public class ManageAirliners extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliners
     */
    private JPanel userprocesscontainer;
    private AirlinerDirectory airlinerdirectory;
    public ManageAirliners(JPanel userprocesscontainer,AirlinerDirectory airlinerdirectory) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airlinerdirectory=airlinerdirectory;
        refreshTable();
    }
    public void refreshTable(){
        int rowCount = manage_airlinersTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)manage_airlinersTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            model.removeRow(i);
        }
        
        for(Airliner al : airlinerdirectory.getAirlinerDirectory()) {
            Object row[] = new Object[1];
            row[0] = al;
            model.addRow(row);
        }
                
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageairlinerworkareaLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manage_airlinersTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        view_airlinerBtn = new javax.swing.JButton();
        add_airlinerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        manageairlinerworkareaLbl.setText("Manage Airliner Work Area");

        manage_airlinersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Airliners"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manage_airlinersTable);

        backBtn.setText("<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        view_airlinerBtn.setText("View Airliner");
        view_airlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_airlinerBtnActionPerformed(evt);
            }
        });

        add_airlinerBtn.setText("Add Airliner");
        add_airlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_airlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(manageairlinerworkareaLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view_airlinerBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(add_airlinerBtn)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(manageairlinerworkareaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(removeBtn)
                    .addComponent(view_airlinerBtn)
                    .addComponent(add_airlinerBtn))
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
         int row = manage_airlinersTable.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airliner al = (Airliner)manage_airlinersTable.getValueAt(row, 0);
        airlinerdirectory.deleteAirliner(al);
        refreshTable();
    }//GEN-LAST:event_removeBtnActionPerformed

    private void add_airlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_airlinerBtnActionPerformed
        // TODO add your handling code here:
        AddAirliner add_airliner = new AddAirliner(userprocesscontainer, airlinerdirectory);
        userprocesscontainer.add("AddAirliner", add_airliner);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_add_airlinerBtnActionPerformed

    private void view_airlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_airlinerBtnActionPerformed
        // TODO add your handling code here:
        int row = manage_airlinersTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Airliner al = (Airliner)manage_airlinersTable.getValueAt(row, 0);
        ViewAirliner view_airliner = new ViewAirliner(userprocesscontainer, al);
        userprocesscontainer.add("ViewAirliner", view_airliner);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_view_airlinerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_airlinerBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manage_airlinersTable;
    private javax.swing.JLabel manageairlinerworkareaLbl;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton view_airlinerBtn;
    // End of variables declaration//GEN-END:variables
}
