/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgencyRole;
import Business.AirlinerDirectory;
import java.awt.CardLayout;

import javax.swing.JPanel;


/**
 *
 *  @author lENOVO PC
 */
public class TravelAgencyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgencyWorkAreaJPanel
     */
    private JPanel userproesscontainer;
    private AirlinerDirectory airlinerdirectory;
    
    public TravelAgencyWorkAreaJPanel(JPanel userproesscontainer,AirlinerDirectory airlinerdirectory) {
        initComponents();
        this.userproesscontainer = userproesscontainer;
        this.airlinerdirectory = airlinerdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardtravelagencyBtn = new javax.swing.JLabel();
        manageairlinerBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        dashboardtravelagencyBtn.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        dashboardtravelagencyBtn.setText("DASHBOARD : TRAVEL AGENCY");

        manageairlinerBtn.setText("Manage Airliners>>");
        manageairlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageairlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(dashboardtravelagencyBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(manageairlinerBtn)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(dashboardtravelagencyBtn)
                .addGap(54, 54, 54)
                .addComponent(manageairlinerBtn)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageairlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageairlinerBtnActionPerformed
        // TODO add your handling code here:
        ManageAirliners manage_airliner_panel = new ManageAirliners(userproesscontainer, airlinerdirectory);
        userproesscontainer.add("ManageAirliners", manage_airliner_panel);
        CardLayout layout = (CardLayout)userproesscontainer.getLayout();
        layout.next(userproesscontainer);
    }//GEN-LAST:event_manageairlinerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardtravelagencyBtn;
    private javax.swing.JButton manageairlinerBtn;
    // End of variables declaration//GEN-END:variables
}
