/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Interface.airliner.AirlinerDirectoryJPanel;
import java.awt.CardLayout;
import Business.*;
import Interface.manage.LoginJPanel;
import Interface.manage.WorkAreaJPanel;


/**
 *
 * @author lENOVO PC
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private  airliner_directory airliner1;
    private airliner a;
   
    public MainJFrame() {
        initComponents();
        airliner1=new airliner_directory();
        a = new airliner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        LeftjPanel = new javax.swing.JPanel();
        btnagency = new javax.swing.JButton();
        btnairliner = new javax.swing.JButton();
        btncustomers = new javax.swing.JButton();
        RightjPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LeftjPanel.setBackground(new java.awt.Color(204, 0, 0));

        btnagency.setBackground(new java.awt.Color(0, 153, 153));
        btnagency.setText("Travel Agency");
        btnagency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagencyActionPerformed(evt);
            }
        });

        btnairliner.setBackground(new java.awt.Color(0, 153, 153));
        btnairliner.setText("Manage Airliners");
        btnairliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnairlinerActionPerformed(evt);
            }
        });

        btncustomers.setBackground(new java.awt.Color(0, 153, 153));
        btncustomers.setText("Customers");

        javax.swing.GroupLayout LeftjPanelLayout = new javax.swing.GroupLayout(LeftjPanel);
        LeftjPanel.setLayout(LeftjPanelLayout);
        LeftjPanelLayout.setHorizontalGroup(
            LeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftjPanelLayout.createSequentialGroup()
                .addGroup(LeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnairliner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnagency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LeftjPanelLayout.setVerticalGroup(
            LeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftjPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnagency)
                .addGap(43, 43, 43)
                .addComponent(btnairliner)
                .addGap(45, 45, 45)
                .addComponent(btncustomers)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(LeftjPanel);

        RightjPanel.setBackground(new java.awt.Color(102, 102, 102));
        RightjPanel.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(RightjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagencyActionPerformed
         AirlinerDirectoryJPanel adPanel = new AirlinerDirectoryJPanel(RightjPanel,airliner1 );
         RightjPanel.add("AirlinerDirectory", adPanel);
         CardLayout layout =(CardLayout)RightjPanel.getLayout();
         layout.next(RightjPanel);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnagencyActionPerformed

    private void btnairlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnairlinerActionPerformed
         LoginJPanel Panel = new LoginJPanel(RightjPanel,airliner1);
         RightjPanel.add("ManageAirlinerCatalog", Panel);
         CardLayout layout =(CardLayout)RightjPanel.getLayout();
         layout.next(RightjPanel);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnairlinerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftjPanel;
    private javax.swing.JPanel RightjPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnagency;
    private javax.swing.JButton btnairliner;
    private javax.swing.JButton btncustomers;
    // End of variables declaration//GEN-END:variables
}
