/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;

import Business.Airliner;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.Airplane;
import java.awt.CardLayout;
import java.awt.Component;
import UserInterface.TravelAgencyRole.ManageAirliners;


/**
 *
 * @author lENOVO PC
 */
public class AddNewAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewAirplaneJPanel
     */
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public AddNewAirplaneJPanel(JPanel userprocesscontainer,Airliner airliner) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addnewairplaneLbl = new javax.swing.JLabel();
        airplanenameLbl = new javax.swing.JLabel();
        airplaneIdLbl = new javax.swing.JLabel();
        airplanePriceLbl = new javax.swing.JLabel();
        airplane_name_Textfield = new javax.swing.JTextField();
        airplane_id_Textfield = new javax.swing.JTextField();
        airplane_price_Textfield = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        addairplaneBtn = new javax.swing.JButton();
        sourceLbl = new javax.swing.JLabel();
        destinationLbl = new javax.swing.JLabel();
        departuredateLbl = new javax.swing.JLabel();
        preferredtimeLbl = new javax.swing.JLabel();
        source_Textfield = new javax.swing.JTextField();
        destination_Textfield = new javax.swing.JTextField();
        deaparturedate_Textfield = new javax.swing.JTextField();
        preferredtime_Textfield = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 0, 0));

        addnewairplaneLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        addnewairplaneLbl.setText("Add New Airplane");

        airplanenameLbl.setText("Airplane Name");

        airplaneIdLbl.setText("Airplane Id");

        airplanePriceLbl.setText("Airplane Price");

        airplane_id_Textfield.setEnabled(false);

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addairplaneBtn.setText("Add Airplane");
        addairplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addairplaneBtnActionPerformed(evt);
            }
        });

        sourceLbl.setText("Source");

        destinationLbl.setText("Destination");

        departuredateLbl.setText("Departure Date");

        preferredtimeLbl.setText("Preferred Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(addnewairplaneLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airplanenameLbl)
                            .addComponent(airplaneIdLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sourceLbl)
                                .addComponent(airplanePriceLbl)
                                .addComponent(destinationLbl)
                                .addComponent(departuredateLbl)
                                .addComponent(preferredtimeLbl)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(airplane_name_Textfield)
                            .addComponent(airplane_id_Textfield)
                            .addComponent(airplane_price_Textfield)
                            .addComponent(source_Textfield)
                            .addComponent(destination_Textfield)
                            .addComponent(deaparturedate_Textfield)
                            .addComponent(preferredtime_Textfield))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addairplaneBtn)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addnewairplaneLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplanenameLbl)
                    .addComponent(airplane_name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneIdLbl)
                    .addComponent(airplane_id_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplanePriceLbl)
                    .addComponent(airplane_price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceLbl)
                    .addComponent(source_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationLbl)
                    .addComponent(destination_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departuredateLbl)
                    .addComponent(deaparturedate_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preferredtimeLbl)
                    .addComponent(preferredtime_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(addairplaneBtn)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addairplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addairplaneBtnActionPerformed
        // TODO add your handling code here:
//        try{
//            Airplane airplane = airliner.getAirplaneCatalog().addAirplane();
//            if(!airplane_name_Textfield.getText().equals("") && !source_Textfield.getText().equals("") && !destination_Textfield.equals("") && deaparturedate_Textfield.getText().equals("") && !preferredtime_Textfield.equals("") && !airplane_price_Textfield.equals("")){
                Airplane airplane = airliner.getAirplaneCatalog().addAirplane();
            airplane.setAirplaneName(airplane_name_Textfield.getText());
            airplane.setSource(source_Textfield.getText());
            airplane.setDestination(destination_Textfield.getText());
            airplane.setDate(deaparturedate_Textfield.getText());
            airplane.setPreferred(preferredtime_Textfield.getText());
            String stringPrice = airplane_price_Textfield.getText();
            if(stringPrice.isEmpty()==false) {
                int price = Integer.parseInt(stringPrice);
                airplane.setPrice(price);
                
                JOptionPane.showMessageDialog(null, "Airplane successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
                
        }
//            else{
//                JOptionPane.showMessageDialog(null, "Enter the values in the fields"); 
//            }
         
            //}
        //}
//            catch(NumberFormatException e){
//                    JOptionPane.showMessageDialog(null, "Enter valid Values"); 
//                    
//                    }
            
    }//GEN-LAST:event_addairplaneBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backBtnActionPerformed
private void backAction() {
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirplaneCatalogJPanel manageAirplanetCatalogJPanel = (ManageAirplaneCatalogJPanel) component;
        manageAirplanetCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addairplaneBtn;
    private javax.swing.JLabel addnewairplaneLbl;
    private javax.swing.JLabel airplaneIdLbl;
    private javax.swing.JLabel airplanePriceLbl;
    private javax.swing.JTextField airplane_id_Textfield;
    private javax.swing.JTextField airplane_name_Textfield;
    private javax.swing.JTextField airplane_price_Textfield;
    private javax.swing.JLabel airplanenameLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField deaparturedate_Textfield;
    private javax.swing.JLabel departuredateLbl;
    private javax.swing.JLabel destinationLbl;
    private javax.swing.JTextField destination_Textfield;
    private javax.swing.JLabel preferredtimeLbl;
    private javax.swing.JTextField preferredtime_Textfield;
    private javax.swing.JLabel sourceLbl;
    private javax.swing.JTextField source_Textfield;
    // End of variables declaration//GEN-END:variables
}
