/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;
import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author lENOVO PC
 */
public class AirlinerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerWorkAreaJPanel
     */
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public AirlinerWorkAreaJPanel(JPanel userprocesscontainer,Airliner airliner) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardairlinerLbl = new javax.swing.JLabel();
        manageAirlplaneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        dashboardairlinerLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        dashboardairlinerLbl.setText("DASHBOARD: AIRLINER ");

        manageAirlplaneButton.setText("Manage Airplane Catalog>>");
        manageAirlplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlplaneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardairlinerLbl)
                    .addComponent(manageAirlplaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dashboardairlinerLbl)
                .addGap(35, 35, 35)
                .addComponent(manageAirlplaneButton)
                .addContainerGap(201, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirlplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlplaneButtonActionPerformed
        // TODO add your handling code here:
        ManageAirplaneCatalogJPanel manage_airplane_catalog = new ManageAirplaneCatalogJPanel(userprocesscontainer, airliner);
        userprocesscontainer.add("ManageAirplaneCatalogJPanel",manage_airplane_catalog);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_manageAirlplaneButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardairlinerLbl;
    private javax.swing.JButton manageAirlplaneButton;
    // End of variables declaration//GEN-END:variables
}
