/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;

import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Business.AirplaneCatalog;
import Business.Airplane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lENOVO PC
 */
public class ManageAirplaneCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirplaneCatalogJPanel
     */
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public ManageAirplaneCatalogJPanel(JPanel userprocesscontainer,Airliner airliner) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
        
        airlinerName_Textfield.setText(airliner.getAirlinerName());
        refreshTable();
    }
    
    public void refreshTable() {
        int rowCount = airplaneCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)airplaneCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Airplane ap : airliner.getAirplaneCatalog().getAirplaneCatalog()) {
            Object row[] = new Object[7];
            row[0] = ap;
            row[1] = ap.getAirlinerCode();
            row[2] = ap.getPrice();
            row[3] = ap.getSource();
            row[4] = ap.getDestination();
            row[5] = ap.getDate();
            row[6] = ap.getPreferred();
            
            model.addRow(row);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageairplanecatalogLbl = new javax.swing.JLabel();
        airlinerNameLbl = new javax.swing.JLabel();
        airlinerName_Textfield = new javax.swing.JTextField();
        searchairplaneBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneCatalog = new javax.swing.JTable();
        viewairplanedetailsBtn = new javax.swing.JButton();
        addnewairplaneBtn = new javax.swing.JButton();
        delete_airplane_detailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        manageairplanecatalogLbl.setText("Manage Airplane Catalog");

        airlinerNameLbl.setText("Airliner");

        searchairplaneBtn.setText("Search>>");
        searchairplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchairplaneBtnActionPerformed(evt);
            }
        });

        airplaneCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Airplane Name", "Airplane Id", "price", "source", "destination", "date", "preferred"
            }
        ));
        jScrollPane1.setViewportView(airplaneCatalog);

        viewairplanedetailsBtn.setText("View Airplane Details");
        viewairplanedetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewairplanedetailsBtnActionPerformed(evt);
            }
        });

        addnewairplaneBtn.setText("Add Airplane Details");
        addnewairplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewairplaneBtnActionPerformed(evt);
            }
        });

        delete_airplane_detailsBtn.setText("Delete Airplane details");
        delete_airplane_detailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_airplane_detailsBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(manageairplanecatalogLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airlinerNameLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(airlinerName_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchairplaneBtn)))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete_airplane_detailsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addnewairplaneBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewairplanedetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageairplanecatalogLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airlinerNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerName_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchairplaneBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewairplanedetailsBtn)
                    .addComponent(delete_airplane_detailsBtn)
                    .addComponent(backBtn)
                    .addComponent(addnewairplaneBtn))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void searchairplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchairplaneBtnActionPerformed
        // TODO add your handling code here:
        SearchForAirplaneJPanel search_airplane_panel = new SearchForAirplaneJPanel(userprocesscontainer, airliner);
        userprocesscontainer.add("SearchForAirplaneJPanel", search_airplane_panel);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_searchairplaneBtnActionPerformed

    private void delete_airplane_detailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_airplane_detailsBtnActionPerformed
        // TODO add your handling code here:
         int row = airplaneCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airplane ap = (Airplane)airplaneCatalog.getValueAt(row, 0);
        airliner.getAirplaneCatalog().deleteAirplane(ap);
        refreshTable();
    }//GEN-LAST:event_delete_airplane_detailsBtnActionPerformed

    private void addnewairplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewairplaneBtnActionPerformed
        // TODO add your handling code here:
        AddNewAirplaneJPanel cnpjp = new AddNewAirplaneJPanel(userprocesscontainer, airliner);
        userprocesscontainer.add("AddNewAirplaneJPanel",cnpjp);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_addnewairplaneBtnActionPerformed

    private void viewairplanedetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewairplanedetailsBtnActionPerformed
        // TODO add your handling code here:
        int row = airplaneCatalog.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Airplane ap = (Airplane)airplaneCatalog.getValueAt(row, 0);
        ViewAirplaneDetailJPanel view_airliner_panel = new ViewAirplaneDetailJPanel(userprocesscontainer, ap);
        userprocesscontainer.add("ViewProductDetailJPanelSupplier", view_airliner_panel);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_viewairplanedetailsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewairplaneBtn;
    private javax.swing.JLabel airlinerNameLbl;
    private javax.swing.JTextField airlinerName_Textfield;
    private javax.swing.JTable airplaneCatalog;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton delete_airplane_detailsBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageairplanecatalogLbl;
    private javax.swing.JButton searchairplaneBtn;
    private javax.swing.JButton viewairplanedetailsBtn;
    // End of variables declaration//GEN-END:variables
}
