/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;

import Business.Airliner;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Airplane;

/**
 *
 * @author lENOVO PC
 */
public class SearchForAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchForAirplaneJPanel
     */
    private JPanel userprocesscontainer;
    private Airliner airliner;
    public SearchForAirplaneJPanel(JPanel userprocesscontainer,Airliner airliner) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airliner=airliner;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchforairplaneLbl = new javax.swing.JLabel();
        airplaneIdLbl = new javax.swing.JLabel();
        airplaneId_Textfield = new javax.swing.JTextField();
        searchnowBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 0, 0));

        searchforairplaneLbl.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        searchforairplaneLbl.setText("Search For Airplane");

        airplaneIdLbl.setText("AirplaneId");

        searchnowBtn.setText("Search Now>>");
        searchnowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnowBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchnowBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchforairplaneLbl)
                            .addComponent(airplaneId_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn)
                            .addComponent(airplaneIdLbl))
                        .addGap(44, 197, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchforairplaneLbl)
                .addGap(28, 28, 28)
                .addComponent(airplaneIdLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airplaneId_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchnowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchnowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnowBtnActionPerformed
        // TODO add your handling code here:
        Airplane airplane;
        int AirplaneId = Integer.parseInt(airplaneId_Textfield.getText());
        airplane = airliner.getAirplaneCatalog().searchAirplane(AirplaneId);
        ViewAirplaneDetailJPanel vpdjp = new ViewAirplaneDetailJPanel(userprocesscontainer, airplane);
        userprocesscontainer.add("ViewAirplaneDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.next(userprocesscontainer);
    }//GEN-LAST:event_searchnowBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        CardLayout layout = (CardLayout)userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airplaneIdLbl;
    private javax.swing.JTextField airplaneId_Textfield;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel searchforairplaneLbl;
    private javax.swing.JButton searchnowBtn;
    // End of variables declaration//GEN-END:variables
}
