/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;

import Business.Airliner;
import Business.Airplane;
import javax.swing.JPanel;
import Business.AirplaneCatalog;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author lENOVO PC
 */
public class ViewAirplaneDetailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneDetailJPanel
     */
    private JPanel userprocesscontainer;
    private Airplane airplane;
    public ViewAirplaneDetailJPanel(JPanel userprocesscontainer,Airplane airplane) {
        initComponents();
        this.userprocesscontainer=userprocesscontainer;
        this.airplane=airplane;
        populate();
        
        
    }
    public void populate(){
        airplane_V_name_Textfield.setText(airplane.getAirplaneName());
        airplane_V_id_Textfield.setText(convertInteger(airplane.getAirlinerCode()));
        airplane_V_price_Textfield.setText(convertInteger(airplane.getPrice()));
        source_Textfield1.setText(airplane.getSource());
        destination_Textfield1.setText(airplane.getDestination());
        date_Textfield1.setText(airplane.getDate());
        preferred_Textfield1.setText(airplane.getPreferred());
    }
public static String convertInteger(int i) {
        return Integer.toString(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewairplanedetailsLbl = new javax.swing.JLabel();
        airplaneVnameLbl = new javax.swing.JLabel();
        airplaneVidLbl = new javax.swing.JLabel();
        airplaneVpriceLbl = new javax.swing.JLabel();
        airplane_V_name_Textfield = new javax.swing.JTextField();
        airplane_V_id_Textfield = new javax.swing.JTextField();
        airplane_V_price_Textfield = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        source1Lbl = new javax.swing.JLabel();
        destination1Lbl = new javax.swing.JLabel();
        Date1Lbl = new javax.swing.JLabel();
        Preferred1Lbl = new javax.swing.JLabel();
        source_Textfield1 = new javax.swing.JTextField();
        destination_Textfield1 = new javax.swing.JTextField();
        date_Textfield1 = new javax.swing.JTextField();
        preferred_Textfield1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 0, 0));

        viewairplanedetailsLbl.setText("View Airplane Details");

        airplaneVnameLbl.setText("Airplane Name");

        airplaneVidLbl.setText("Airplane id");

        airplaneVpriceLbl.setText("Airplane price");

        backBtn.setText("<<back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Details");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        source1Lbl.setText("Source");

        destination1Lbl.setText("destination");

        Date1Lbl.setText("Date");

        Preferred1Lbl.setText("Preferred");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Preferred1Lbl)
                            .addComponent(Date1Lbl)
                            .addComponent(destination1Lbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(airplaneVidLbl)
                                        .addComponent(airplaneVnameLbl)
                                        .addComponent(airplaneVpriceLbl)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(source1Lbl))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewairplanedetailsLbl)
                            .addComponent(airplane_V_name_Textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(airplane_V_id_Textfield)
                            .addComponent(airplane_V_price_Textfield)
                            .addComponent(source_Textfield1)
                            .addComponent(destination_Textfield1)
                            .addComponent(date_Textfield1)
                            .addComponent(preferred_Textfield1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn)
                        .addGap(18, 18, 18)
                        .addComponent(saveBtn)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewairplanedetailsLbl)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneVnameLbl)
                    .addComponent(airplane_V_name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneVidLbl)
                    .addComponent(airplane_V_id_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airplaneVpriceLbl)
                    .addComponent(airplane_V_price_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(source1Lbl)
                    .addComponent(source_Textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destination1Lbl)
                    .addComponent(destination_Textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date1Lbl)
                    .addComponent(date_Textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Preferred1Lbl)
                    .addComponent(preferred_Textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(updateBtn)
                    .addComponent(saveBtn))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        airplane_V_name_Textfield.setEditable(true);
       airplane_V_price_Textfield.setEditable(true);
        source_Textfield1.setEditable(true);
         destination_Textfield1.setEditable(true);
          date_Textfield1.setEditable(true);
           preferred_Textfield1.setEditable(true);
          
       saveBtn.setEnabled(true);
       updateBtn.setEnabled(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        airplane_V_name_Textfield.setEditable(false);
            airplane_V_price_Textfield.setEditable(false);
            source_Textfield1.setEditable(false);
            destination_Textfield1.setEnabled(false);
            date_Textfield1.setEnabled(false);
            preferred_Textfield1.setEnabled(false);
            saveBtn.setEnabled(false);
            updateBtn.setEnabled(true);
            
//            try
//        {
//            if(!airplane_V_name_Textfield.getText().equals("")&& !txtPrice.getText().equals("") && !txtAvailablity.getText().equals("") && !txtDesc.getText().equals(""))
        
        airplane.setPrice(Integer.parseInt(airplane_V_price_Textfield.getText()));
        airplane.setAirplaneName(airplane_V_name_Textfield.getText());
        airplane.setSource(source_Textfield1.getText());
        airplane.setDestination(destination_Textfield1.getText());
        airplane.setDate(date_Textfield1.getText());
        airplane.setPreferred(preferred_Textfield1.getText());
        
        JOptionPane.showMessageDialog(null, "details saved successfully"); 
    }//GEN-LAST:event_saveBtnActionPerformed

    private void backAction() {
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirplaneCatalogJPanel manageAirplaneCatalogJPanel = (ManageAirplaneCatalogJPanel) component;
        manageAirplaneCatalogJPanel.refreshTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date1Lbl;
    private javax.swing.JLabel Preferred1Lbl;
    private javax.swing.JLabel airplaneVidLbl;
    private javax.swing.JLabel airplaneVnameLbl;
    private javax.swing.JLabel airplaneVpriceLbl;
    private javax.swing.JTextField airplane_V_id_Textfield;
    private javax.swing.JTextField airplane_V_name_Textfield;
    private javax.swing.JTextField airplane_V_price_Textfield;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField date_Textfield1;
    private javax.swing.JLabel destination1Lbl;
    private javax.swing.JTextField destination_Textfield1;
    private javax.swing.JTextField preferred_Textfield1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel source1Lbl;
    private javax.swing.JTextField source_Textfield1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel viewairplanedetailsLbl;
    // End of variables declaration//GEN-END:variables
}
